
generic:
	install generic-custom.ent custom.ent
	install generic-links.xsl links.xsl
	install generic-prefix.txt prefix.txt
	install generic-stylesheet.css stylesheet.css
	install generic-stylesheet.xsl stylesheet.xsl

clean:
	rm -f custom.ent links.xsl prefix.txt stylesheet.css stylesheet.xsl
